src/CowboyDuel/AdminBundle/Entity/Admin.php
<?php
namespace CowboyDuel\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM,
    Symfony\Component\Security\Core\User\UserInterface;

/**
 * CowboyDuel\AadminBundle\Entity\Admin
 *
 * @ORM\Table(name="admin")
 * @ORM\Entity
 */
class Admin extends AbstractEntity implements UserInterface {
	/**
	 * @var string $name
	 *
	 * @ORM\Column(type="string")
	 */
	private $name;

	/**
	 * @var string $email
	 *
	 * @ORM\Column(type="string")
	 */
	private $email;

	/**
	 * @var string $password
	 *
	 * @ORM\Column(type="string")
	 */
	private $password;

	/**
	 * Set name
	 *
	 * @param string $name
	 * @return Admin
	 */
	public function setName($name) {
		$this->name = $name;

		return $this;
	}

	/**
	 * Get name
	 *
	 * @return string 
	 */
	public function getName() {
		return $this->name;
	}

	/**
	 * Set email
	 *
	 * @param string $email
	 * @return Admin
	 */
	public function setEmail($email) {
		$this->email = $email;

		return $this;
	}

	/**
	 * Get email
	 *
	 * @return string 
	 */
	public function getEmail() {
		return $this->email;
	}

	/**
	 * Set password
	 *
	 * @param string $password
	 * @return Admin
	 */
	public function setPassword($password) {
		$this->password = $password;

		return $this;
	}

	/**
	 * Get password
	 *
	 * @return string 
	 */
	public function getPassword() {
		return $this->password;
	}
	
	public function getRoles() 
	{
		return array('ROLE_ADMIN');
	}
	
	public function getSalt() 
	{
		return '';
	}
	
	public function getUsername() 
	{
		return $this->name;
	}
	
	public function eraseCredentials() {}

}

src/CowboyDuel/AdminBundle/Resources/views/layout.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>{% block title %}Welcome!{% endblock %}</title>    
        
        {% set uriRes = 'bundles/cowboydueladmin/' %}        
                
        {% block stylesheets %}{% endblock %}      
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/style.css') }}" type="text/css"/>          
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/forms.css') }}" type="text/css"/>
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/forms-btn.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/menu.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/style_text.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/datatables.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/fullcalendar.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/pirebox.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/modalwindow.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/statics.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/tabs-toggle.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/system-message.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/tooltip.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/wizard.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/wysiwyg.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/wysiwyg.modal.css') }}" type="text/css"/> 
        <link rel="stylesheet" href="{{ asset(uriRes ~ 'css/wysiwyg-editor.css') }}" type="text/css"/> 
       
        {% block javascript %}{% endblock %}
        <script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery-1.7.1.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.ui.1.8.17.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.ui.select.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.ui.spinner.js') }}"></script>		
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.backgroundPosition.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.placeholder.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/superfish.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/supersubs.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.datatables.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/fullcalendar.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.smartwizard-2.0.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/pirobox.extended.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.tipsy.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.elastic.source.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.customInput.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.validate.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.metadata.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.filestyle.mini.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.filter.input.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.flot.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.flot.pie.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.flot.resize.min.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.graphtable-0.2.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/jquery.wysiwyg.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/controls/wysiwyg.image.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/controls/wysiwyg.link.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/controls/wysiwyg.table.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/plugins/wysiwyg.rmFormat.js') }}"></script>
		<script type="text/javascript" src="{{ asset(uriRes ~ 'js/costum.js') }}"></script>  
        
        <link rel="shortcut icon" href="{{ asset('') }}" />                       
    </head>
    <body>       
     {% block body%}  
        <div id="wrapper">
          {% block wrapper%}
			<div id="container">	
			  {% block content%}
				<div class="hide-btn top"></div>
				<div class="hide-btn center"></div>
				<div class="hide-btn bottom"></div>		
				<div id="top">
					<h1 id="logo"><a href="{{ path("admin_index") }}"></a></h1>
					<div id="labels">
						<ul>
							<li><a href="#" class="user"><span class="bar">Welcome {{ app.user.username }}</span></a></li>
							<li><a href="#" class="settings"></a></li>
							<li class="subnav">
								<a href="#" class="messages"></a>
								<ul>
									<li><a href="#">New message</a></li>
									<li><a href="#">Inbox</a></li>
									<li><a href="#">Outbox</a></li>
									<li><a href="#">Trash</a></li>
								</ul>
							</li>
							<li><a href="{{ path('admin_auth_logout') }}" class="logout"></a></li>
						</ul>
					</div>
					<div id="menu">
						<ul> 
							<li {% if location == 'store_index' %} class="current" {% endif %}>
								<a href="{{ path("store_index") }}">Товари</a>
								<ul> 
									<li {% if location == 'store_add_item' %} class="current" {% endif %}>
										<a href="{{ path("store_add_item") }}">Додати товар</a></li>
									<li {% if location == 'store_purchased_list' %} class="current" {% endif %}>
										<a href="{{ path("store_purchased_list") }}">Куплені</a></li>
									<li><a href="{{ path("store_list_items_json") }}" target="blank">
										Відіслати на S3</a></li>															
								</ul>								
							</li>
							<li {% if location == 'users_index' %} class="current" {% endif %}>
								<a href="{{ path("users_index") }}">Гравці</a>
								<ul> 
									<li {% if location == 'users_getFrozen' %} class="current" {% endif %}>
										<a href="{{ path("users_getFrozen") }}">Заморожені</a></li>
									<li {% if location == 'users_getAllBot' %} class="current" {% endif %}>
									<a href="{{ path("users_getAllBot") }}">Боти</a></li>
								</ul>
							</li>
							<li {% if location == '#' %} class="current" {% endif %}>
								<a href="#">Статистика</a>
								<ul> 
									<li {% if location == 'admin_duels_in_day' %} class="current" {% endif %}>
										<a href="{{ path("admin_duels_in_day") }}">Дуелі</a></li>
									<li {% if location == 'admin_sales_of_goods' %} class="current" {% endif %}>
										<a href="{{ path("admin_sales_of_goods") }}">Продаж товарів</a></li>
									<li {% if location == 'admin_registered_users_of_percentage' %} class="current" {% endif %}>
										<a href="{{ path("admin_registered_users_of_percentage") }}">Pеєстрація користувачів</a></li>
								</ul>
							</li>														
							{% block menu %}
        					{% endblock %}
						</ul>
					</div>
				</div>		
				<div id="left">
					<!--  
					<div class="box search">
						<div class="content">
							<form action="">
								<input type="text" value="" placeholder="Search" />
								<button type="submit"></button>
							</form>
						</div>
					</div>	
					-->
					<div class="box statics">
				      <div class="content">
					    <ul>
						    <li><h2>Статистика</h2></li>
						    <li>Зареєстровано <div class="info blue"><span>{{ data.countRegisteredUsers }}</span></div></li>
						    <li>Зареєстровано<br>в Facebook <div class="info green"><span>{{ data.countRegisteredUsersFromFacebook }}</span></div></li>
						    <li>Воювали в дуелі <div class="info black"><span>{{ data.countUsersAttendedDuels }}</span></div></li>
						    <li>Відношення до<br>кількості користувачів <div class="info black"><span>{{ data.ratioUsersOfRolledQuantityDuel }}</span></div></li>
					    </ul>
				      </div>
				    </div>
					{% block left %}
        			{% endblock %}	
				</div>		
				<div id="right">	
					{% block right %}
        			{% endblock %}			
				</div>
			  {% endblock %}		
			</div>
			{% block containerFother %}
            {% endblock %}
		</div> 
	  {% endblock %}     
    </body>
    {% endblock %}
</html>